In [46]:
import pandas as pd

In [47]:
data = {
    "Employee_ID": [101, 102, 103, 104, 102, 105, 103],
    "Name": ["Amit", "Priya", "Rahul", "Sneha", "Priya", "Rohit", "Rahul"],
    "Age": [25, 28, 30, 27, 28, 35, 30],
    "Department": ["IT", "HR", "Finance", "IT", "HR", "Marketing", "Finance"],
    "Salary": [45000, 50000, 60000, 48000, 50000, 55000, 60000]
}

In [48]:
df=pd.DataFrame(data)
df

   Employee_ID   Name  Age Department  Salary
0          101   Amit   25         IT   45000
1          102  Priya   28         HR   50000
2          103  Rahul   30    Finance   60000
3          104  Sneha   27         IT   48000
4          102  Priya   28         HR   50000
5          105  Rohit   35  Marketing   55000
6          103  Rahul   30    Finance   60000

In [57]:
df.drop_duplicates(keep="first")

   Employee_ID   Name  Age Department  Salary
0          101   Amit   25         IT   45000
1          102  Priya   28         HR   50000
2          103  Rahul   30    Finance   60000
3          104  Sneha   27         IT   48000
5          105  Rohit   35  Marketing   55000

In [59]:
df.drop_duplicates(inplace=True)
df

   Employee_ID   Name  Age Department  Salary
0          101   Amit   25         IT   45000
1          102  Priya   28         HR   50000
2          103  Rahul   30    Finance   60000
3          104  Sneha   27         IT   48000
5          105  Rohit   35  Marketing   55000

In [60]:
## Perform on original dataset
dataset=pd.read_csv('Loans.csv')
dataset.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32581    False
32582    False
32583    False
32584    False
32585    False
Length: 32586, dtype: bool

In [61]:
dataset.shape

(32586, 13)

In [64]:
dataset.drop_duplicates(inplace=True)
dataset.shape

(32580, 13)