In [24]:
import pandas as pd

In [25]:
dataset=pd.read_csv('Loans.csv')
dataset.head()

,customer_id,customer_age,customer_income,home_ownership,employment_duration,loan_intent,loan_grade,loan_amnt,loan_int_rate,term_years,historical_default,cred_hist_length,Current_loan_status
0,1.0,22,59000,RENT,123.0,PERSONAL,C,"£35,000.00",16.02,10,Y,3,DEFAULT
1,2.0,21,9600,OWN,5.0,EDUCATION,A,"£1,000.00",11.14,1,NaN,2,NO DEFAULT
2,3.0,25,9600,MORTGAGE,1.0,MEDICAL,B,"£5,500.00",12.87,5,N,3,DEFAULT
3,4.0,23,65500,RENT,4.0,MEDICAL,B,"£35,000.00",15.23,10,N,2,DEFAULT
4,5.0,24,54400,RENT,8.0,MEDICAL,B,"£35,000.00",14.27,10,Y,4,DEFAULT

In [26]:
dataset.shape

(32586, 13)

In [27]:
dataset.isnull().sum()

customer_id                3
customer_age               0
customer_income            0
home_ownership             0
employment_duration      895
loan_intent                0
loan_grade                 0
loan_amnt                  1
loan_int_rate           3116
term_years                 0
historical_default     20737
cred_hist_length           0
Current_loan_status        4
dtype: int64

In [28]:
dataset['historical_default'].fillna(dataset['historical_default'].mode()[0],inplace=True)

C:\Users\dps23\AppData\Local\Temp\ipykernel_16112\2839225429.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['historical_default'].fillna(dataset['historical_default'].mode()[0],inplace=True)

In [29]:
dataset['Current_loan_status'].fillna(dataset['Current_loan_status'].mode()[0],inplace=True)

C:\Users\dps23\AppData\Local\Temp\ipykernel_16112\3201391485.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Current_loan_status'].fillna(dataset['Current_loan_status'].mode()[0],inplace=True)

In [30]:
dataset.isnull().sum()

customer_id               3
customer_age              0
customer_income           0
home_ownership            0
employment_duration     895
loan_intent               0
loan_grade                0
loan_amnt                 1
loan_int_rate          3116
term_years                0
historical_default        0
cred_hist_length          0
Current_loan_status       0
dtype: int64

One Hot coding // pandas Method

In [31]:
en_data=dataset[["historical_default","Current_loan_status"]]
en_data

      historical_default Current_loan_status
0                      Y             DEFAULT
1                      Y          NO DEFAULT
2                      N             DEFAULT
3                      N             DEFAULT
4                      Y             DEFAULT
...                  ...                 ...
32581                  Y          NO DEFAULT
32582                  Y          NO DEFAULT
32583                  N             DEFAULT
32584                  Y          NO DEFAULT
32585                  Y          NO DEFAULT

[32586 rows x 2 columns]

In [ ]:
pd.get_dummies(en_data)

,historical_default_N,historical_default_Y,Current_loan_status_DEFAULT,Current_loan_status_NO DEFAULT
0,False,True,True,False
1,False,True,False,True
2,True,False,True,False
3,True,False,True,False
4,False,True,True,False
...,...,...,...,...
32581,False,True,False,True
32582,False,True,False,True
32583,True,False,True,False
32584,False,True,False,True
32585,False,True,False,True

In [36]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32586 entries, 0 to 32585
Data columns (total 4 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   historical_default_N            32586 non-null  bool
 1   historical_default_Y            32586 non-null  bool
 2   Current_loan_status_DEFAULT     32586 non-null  bool
 3   Current_loan_status_NO DEFAULT  32586 non-null  bool
dtypes: bool(4)
memory usage: 127.4 KB

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [43]:
ohe=OneHotEncoder(drop='first')
ohe.fit_transform(en_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 52611 stored elements and shape (32586, 2)>

In [48]:
ar=ohe.fit_transform(en_data).toarray()
ar

array([[1., 0.],
       [1., 1.],
       [0., 0.],
       ...,
       [0., 0.],
       [1., 1.],
       [1., 1.]], shape=(32586, 2))

In [49]:
pd.DataFrame(ar,columns=["historical_default_Y","Current_loan_status_NO DEFAULT"])

       historical_default_Y  Current_loan_status_NO DEFAULT
0                       1.0                             0.0
1                       1.0                             1.0
2                       0.0                             0.0
3                       0.0                             0.0
4                       1.0                             0.0
...                     ...                             ...
32581                   1.0                             1.0
32582                   1.0                             1.0
32583                   0.0                             0.0
32584                   1.0                             1.0
32585                   1.0                             1.0

[32586 rows x 2 columns]